name: CI

on:
  pull_request:
    branches: [ 'master' ]
  push:
    branches: [ 'master' ]
  release:
    types: [ 'created' ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run tests
        run: cargo test --release --verbose --workspace
  linuxbuild:
    name: Create Linux Package
    runs-on: ubuntu-latest
    needs:
      - test
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.*'
      - name: Setup DEB/RPM build
        run: sudo apt update && sudo apt install rpm
      - name: Linux packages
        run: |
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
            VERSION="${GITHUB_REF_NAME#v}"
          else
            VERSION="0.0.0"
          fi
          cmake -S ./dnpm-validator-ui -B build -DCMAKE_BUILD_TYPE=Release -DCPACK_PACKAGE_VERSION="$VERSION"
          cmake --build build --config Release
          cpack --config build/CPackConfig.cmake -G DEB -B build/packages
          cpack --config build/CPackConfig.cmake -G RPM -B build/packages
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dnpm-validator-ui
          path: build/packages/*
          retention-days: 1
      # Only run, if release is created
      - name: Release
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        uses: softprops/action-gh-release@v3
        with:
          files: |
            build/packages/*.deb
            build/packages/*.rpm
      - name: Upload to DNPM-Repository
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        run: |
          curl -L --user dnpm:${{ secrets.PACKAGE_TOKEN }} --upload-file build/packages/*.deb ${{ vars.DEB_UPLOAD_URL }}
          curl -L --user dnpm:${{ secrets.PACKAGE_TOKEN }} --upload-file build/packages/*.rpm ${{ vars.RPM_UPLOAD_URL }}
  windowsbuild:
    name: Create Windows Package
    runs-on: windows-2022
    needs:
      - test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.*'
          arch: win64_msvc2022_64
      - name: Windows installer and ZIP
        run: |
          if ($env:GITHUB_REF -like "refs/tags/*") {
            $version = $env:GITHUB_REF_NAME -replace '^v', ''
          } else {
            $version = "0.0.0"
          }
          "VERSION=$version" >> $env:GITHUB_ENV
          cmake -S ./dnpm-validator-ui -B build -G "Visual Studio 17 2022" -A x64 -DCPACK_PACKAGE_VERSION="$version"
          cmake --build build --config Release
          cmake --install build --config Release --prefix build/package
          cpack --config build/CPackConfig.cmake -G NSIS -B build/packages
          cpack --config build/CPackConfig.cmake -G ZIP -B build/packages
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dnpm-validator-ui
          path: build/packages/*
          retention-days: 1
      # Only run, if release is created
      - name: Release
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        uses: softprops/action-gh-release@v3
        with:
          files: |
            build/packages/*.exe
            build/packages/*.zip